apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ct.fullname" . }}-secrets
  labels: {{- include "ct.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  ANON_KEY: {{ .Values.secrets.anonKey | quote }}
  SERVICE_ROLE_KEY: {{ .Values.secrets.serviceRoleKey | quote }}
  REALTIME_SECRET_KEY_BASE: {{ .Values.secrets.realtimeSecretKeyBase | quote }}
  SMTP_PASS: {{ .Values.smtp.pass | quote }}
  GOOGLE_SECRET: {{ .Values.supabase.auth.google.secret | quote }}
  AI_API_KEY: {{ .Values.ai.apiKey | quote }}
